### ISSUE TITLE
file not found for module `raft`

### ISSUE THREAD

**Issue by goyas** [erikgrinaker/toydb#39]
hi，when I checkout  commit fe8f3221529ca985ef11757506352c35600907f0. error occurred as follow:
file not found for module `raft`
![image](https://user-images.githubusercontent.com/54054850/87656764-804b7880-c78c-11ea-9a84-5aba214800bb.png)

**Comment by erikgrinaker** [comment]
Hi @goyas! In old versions of toyDB, `raft.rs` was a gRPC service generated from Protobuf schemas via `build.rs`. I suppose this may not be generated correctly in Docker.
