### ISSUE TITLE
I like this repo

### ISSUE THREAD

**Issue by pkking** [erikgrinaker/toydb#42]
Hi Erik,
Im new to rust and database and i think this repo is a amazing project for learning both things.
Want to contribute some code but i did not find any code of conduct or CONTRIBUTING things.
Is there anything i should notice about that?

**Comment by erikgrinaker** [comment]
Thanks @pkking, glad you like it!

This project was mostly a one-off personal project, and I'm not really planning to actively improve or maintain it (although I may pick it up again sometime). Any significant changes are better done in your own fork, but PRs for minor improvements (such as updates to newer Rust versions) are welcome and appreciated.
