### ISSUE TITLE
test cluster::isolation::anomaly_dirty_read blocks indefinitely

### ISSUE THREAD

**Issue by bud-adamas** [erikgrinaker/toydb#44]
It looks like:
```
     Running target/debug/deps/tests-28925d9acf338694

running 1 test
test cluster::isolation::anomaly_dirty_read ... 

```

It seems blocked within tokio, but I am not falimiar with tokio.

**Comment by erikgrinaker** [comment]
This usully happens because there is another ToyDB process already running that's listening on the same port (the tests use the default port), so some messages get sent to it instead of the test instance.
