### ISSUE TITLE
Run with error

### ISSUE THREAD

**Issue by lijobs** [erikgrinaker/toydb#63]
When I tried to operate this order here, the system said that I run with the error as follows:

cargo run --release --bin toysql
the following packages contain code that will be rejected by a future version of Rust: nom v5.1.2
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running `target/release/toysql`
Error: Internal("Connection refused (os error 111)")

My operation system is Ubuntu22.04 and the rust version is 1.70. Please help me to solve this issue. Thanks!

**Comment by erikgrinaker** [comment]
Hi! "Connection refused" indicates that the toyDB server isn't running. It can be started by running e.g. `cargo run --release --bin toydb`.
