### ISSUE TITLE
test failed issue

### ISSUE THREAD

**Issue by qujihan** [erikgrinaker/toydb#72]
hi, @erikgrinaker , thanks for yor great project!

When I run `cargo test ---test tests` it says `invalid input: table test already exists`, I think I can fix it by deleting the datadir, but I'm not sure where the datadir is set to. 

Can you tell me how I should look at datadir how to view it?

**Comment by erikgrinaker** [comment]
Each test runs in its own isolated data directory, which is deleted when the test exits.

It sounds like there may be stray toyDB processes still running for some reason, possibly from old tests. Try looking for any processes with e.g. `ps aux | grep toydb` and killing them.
